<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Commands\Universities\" />
    <Folder Include="Features\Commands\Questionnaires\" />
    <Folder Include="Features\Commands\Users\" />
    <Folder Include="Features\Queries\Questionnaires\" />
    <Folder Include="Features\Queries\Universities\" />
    <Folder Include="NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Survey.Questionnaire\Survey.Questionnaires.csproj" />
    <ProjectReference Include="..\Survey.University\Survey.University.csproj" />
    <ProjectReference Include="..\Survey.Users\Survey.Users.csproj" />
  </ItemGroup>

</Project>
